version: "3.1"
services:
  db:
    image: postgres:15.2
    ports:
      - 5435:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=p4sswd
      - POSTGRES_USER=postgres
      - POSTGRES_DB=purpledb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  lint:
    image: golangci/golangci-lint
    profiles: ["tools"]
    volumes:
      - .:/app
    working_dir: /app

  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "3334:8080"
    volumes:
      - ./docs:/docs
    environment:
      - SWAGGER_JSON=/docs/api.yaml
      - BASE_URL=/swagger

  migrate:
    image: migrate/migrate:v4.15.2
    profiles: ["tools"]
    volumes:
      - ./db/migrations:/migrations
    entrypoint:
      [
        "migrate",
        "-path",
        "/migrations",
        "-database", "postgres://postgres:p4sswd@db:5432/purpledb?sslmode=disable"
      ]
    command: ["up"]
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
