// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/ervinismu/purplestore/controllers"
	"github.com/ervinismu/purplestore/repository"
	"github.com/ervinismu/purplestore/service"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func InitProductController(db *gorm.DB) controllers.ProductController {
	productRepository := repository.NewProductRepository(db)
	productService := service.NewProductService(productRepository)
	productController := controllers.NewProductController(productService)
	return productController
}

func InitUserController(db *gorm.DB) controllers.UserController {
	userRepository := repository.NewUserRepository(db)
	userService := service.NewUserService(userRepository)
	userController := controllers.NewUserController(userService)
	return userController
}
